[project]
name = "attendance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "face-recognition>=1.3.0",
    "fastapi[standard]>=0.115.11",
    "opencv-python>=4.11.0.86",
    "sqlmodel>=0.0.24",
]
